### ISSUE TITLE
CLI processes non-d.ts files

### ISSUE THREAD

**Issue by rondonjon** [huang2002/dts2md#1]
Thanks for writing this tool.

It seems that the CLI app currently only accepts directory names and not file names as input.

I have tried passing my `dist/` directory to the CLI app, but it seems to be processing all files in the directory and not only the `d.ts` files.

Hence the feature request:

Please offer a way to specify filenames as input OR exlude non-d.ts files from processing when directories are processed.

**Comment by huang2002** [comment]
Thanks for using this tool! ❤️ 

Actually, the CLI app supports file globs as input files, as is mentioned in the [docs](https://github.com/huang2002/dts2md#usage).

So, if you want to process only `.d.ts` files in `dist/`, you can try this:

```bash
$ dts2md "*.d.ts" -i dist
```
